### ISSUE TITLE
Add Recipe Completion Confirmation

### ISSUE THREAD

**Issue by slegec** [tranaj2/CrockPot#6]
Currently, there is no confirmation that the recipe was pulled and added successfully.  Perhaps displaying a preview of what the recipe looks like once it is completed would be beneficial for the user

**Comment by jtranate** [comment]
Yeah, right now I'm just adding our base functionality so that @muryannye can do the UI and such. 

But I agree. We could direct them to the recipe as well as have a label saying it was successfully added: https://getbootstrap.com/docs/4.0/components/alerts/
